apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80     # External port (browser)
      targetPort: 8080    # Internal container port (Flask app)
