name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: stable-healer-418019
        install_components: 'beta'

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/stable-healer-418019/my-repo/my-flask-app .
        docker push us-central1-docker.pkg.dev/stable-healer-418019/my-repo/my-flask-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-flask-app \
          --image us-central1-docker.pkg.dev/stable-healer-418019/my-repo/my-flask-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
